# Generated by Django 4.2.9 on 2024-01-23 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=50)),
                ('completion', models.IntegerField(default=0)),
                ('client', models.CharField(max_length=50, null=True)),
                ('duedate', models.DateField()),
                ('status', models.CharField(choices=[('PLANNING', 'PLANNING'), ('DEVELOPMENT', 'DEVELOPMENT'), ('TESTING', 'TESTING'), ('UAT', 'UAT'), ('LIVE', 'LIVE')], default='PLANNING')),
                ('type', models.CharField(max_length=10, null=True)),
                ('planned_end_date', models.DateField(null=True)),
                ('actual_end_date', models.DateField(null=True)),
                ('planned_start_date', models.DateField(null=True)),
                ('actual_start_date', models.DateField(null=True)),
                ('total_cost', models.IntegerField()),
                ('cost_incurred_percentage', models.FloatField(default=0)),
                ('cost_incurred', models.IntegerField()),
                ('cost_Exceeded', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DESIGN', 'DESIGN'), ('TESTING', 'TESTING'), ('UNITTESTING', 'UNITTESTING'), ('DEVELOPMENT', 'DEVELOPMENT')], default='DESIGN')),
                ('duedate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintname', models.CharField(max_length=50)),
                ('endson', models.DateField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='management.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='management.tag'),
        ),
    ]
