# Generated by Django 4.2.9 on 2024-01-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_client_comments_notes_status_alter_sprints_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='management.client'),
        ),
    ]
