# Generated by Django 4.2.9 on 2024-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_projects_stakeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stackname', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
    ]
