# Generated by Django 4.2.9 on 2024-01-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_comments_comment_rename_notes_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimate',
            field=models.IntegerField(default=0),
        ),
    ]
