# Generated by Django 4.2.9 on 2024-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate',
            field=models.CharField(default='0 hr', max_length=10),
        ),
    ]
