version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
