# Generated by Django 4.2.9 on 2024-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_is_active_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staf',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
