# Generated by Django 4.2.9 on 2024-01-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_is_staf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staf',
        ),
    ]
